'use strict';

var React = require('react-native');

var styles = React.StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'flex-start',
        alignItems: 'stretch',
        backgroundColor: '#EFEFEF',
    },
    topbar: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        elevation: 5,
    },
    topbar__titlecontainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    topbar__title: {
        fontFamily: 'sans-serif-thin',
        fontSize: 18,
    },
    topbar__menubuttoncontainer: {
        height: 32,
        width: 32,
        alignItems: 'center',
        justifyContent: 'center',
        position: 'absolute',
        right: 16,
        top: 16,
        bottom: 0,
    },
    topbar__menubutton: {
        height: 16,
        width: 16,
    },
    topbar__navigation: {
        height: 32,
        flexDirection: 'row',
        flexWrap: 'nowrap',
        backgroundColor: '#EFEFEF',
        alignSelf: 'stretch',
        alignItems: 'stretch',
        justifyContent: 'center',
    },
    topbar__previous: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    topbar__next: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    topbar__button: {
        width: 16,
        height: 16,
    },
    main: {
        flex: 1,
    },
    main__view: {
        flex: 1,
        padding: 8,
    },
    main__title: {
        color: '#C2C2C2',
        paddingTop: 8,
        paddingBottom: 8,
        textAlign: 'left',
    },
    main__weektitle: {
        color: '#3E4A51',
        fontSize: 12,
        fontWeight: 'bold',
        marginTop: 16,
    },
    subject: {
        backgroundColor: '#FFFFFF',
        padding: 16,
        marginBottom: 12,
        alignSelf: 'stretch',
        borderBottomWidth: 1,
        borderBottomColor: '#DDDDDD',
    },
    subject__main: {  
        alignItems: 'flex-start',
        flexDirection: 'row',
        flexWrap: 'nowrap',
    },
    subject__info: {
        marginTop: 32,
    },
    subject__left: {
        flex: 1,
        alignItems: 'flex-start',
    },
    subject__right: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        flexWrap: 'nowrap',
        flexDirection: 'row',
        paddingTop: 5,
    },
    subject__title: {
        color: '#3F4B52',
        fontSize: 18,
        fontFamily: 'sans-serif-thin',
        paddingTop: 0,
        paddingBottom: 4,
    },
    subject__room: {
        color: '#9C9C9C',
        fontSize: 12,
        paddingBottom: 8,
    },
    subject__start: {
        padding: 16,
        paddingTop: 8,
        paddingBottom: 8,
        backgroundColor: '#3E4A51',
        color: '#FFFFFF',
        fontSize: 16,
    },
    subject__end: {
        padding: 16,
        paddingTop: 8,
        paddingBottom: 8,
        backgroundColor: '#49545B',
        color: '#FFFFFF',
        fontSize: 16,
    },
    triangle__blue: {
        width: 0,
        height: 0,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        position: 'absolute',
        left: 0,
        top: 0,
        borderTopWidth: 16,
        borderRightWidth: 16,
        borderBottomWidth: 0,
        borderLeftWidth: 0,
        borderTopColor: '#6699CC',
        borderRightColor: 'transparent',
        borderBottomColor: 'transparent',
        borderLeftColor: 'transparent',
    },
    triangle__green: {
        width: 0,
        height: 0,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        position: 'absolute',
        left: 0,
        top: 0,
        borderTopWidth: 16,
        borderRightWidth: 16,
        borderBottomWidth: 0,
        borderLeftWidth: 0,
        borderTopColor: '#80B8A0',
        borderRightColor: 'transparent',
        borderBottomColor: 'transparent',
        borderLeftColor: 'transparent',
    },
    triangle__orange: {
        width: 0,
        height: 0,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        position: 'absolute',
        left: 0,
        top: 0,
        borderTopWidth: 16,
        borderRightWidth: 16,
        borderBottomWidth: 0,
        borderLeftWidth: 0,
        borderTopColor: '#FFB347',
        borderRightColor: 'transparent',
        borderBottomColor: 'transparent',
        borderLeftColor: 'transparent',
    },
    menu: {
        flex: 1,
        backgroundColor: '#FFFFFF',
    },
    menu__contents: {
        margin: 10,
        fontSize: 15,
        textAlign: 'left',
    },
    menu__subtitle: {
        fontWeight: 'bold',
        fontSize: 12,
        color: '#3E4A51',
        padding: 16,
        marginTop: 16,
        alignSelf: 'stretch',
        borderBottomWidth: 1,
        borderBottomColor: '#E0E0E0',
    },
    menu__semester: {
        padding: 8,
        borderLeftWidth: 4,
        borderLeftColor: '#6699CC',
    },
    menu__semestertitle: {
        fontSize: 14,
        color: '#444444'
    },
    menu__semesterdate: {
        fontSize: 10,
        color: '#9C9C9C',
    },
});

module.exports = styles;